name: ipfsnets
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # 构建路由模块
  fluro:
    git: git://github.com/theyakka/fluro.git
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars: ^2.0.1
  # 汉字转拼音库 https://github.com/flutterchina/lpinyin
  lpinyin: ^1.1.0
  # rxdart https://github.com/ReactiveX/rxdart
  rxdart: ^0.27.1
  flutter_l10n: ^0.1.3
  json_annotation: ^3.1.1
  flutter_screenutil: ^5.0.0
  # https://github.com/flutterchina/dio
  dio: ^4.0.0
  #https://github.com/felangel/bloc
  bloc: ^7.0.0
  flutter_bloc: ^7.0.1
  equatable: ^2.0.0
  #https://github.com/kokohuang/flutter_easyloading
  flutter_easyloading: ^3.0.0
  # 格式化String https://github.com/Naddiseo/dart-sprintf
  sprintf: ^6.0.0
  # WebView插件 https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  webview_flutter: 2.0.9
  # 获取当前设备信息 https://github.com/fluttercommunity/plus_plugins/tree/main/packages/device_info_plus
  device_info_plus: 2.0.1
  get: ^4.1.3
  pull_to_refresh: ^2.0.0
  # https://github:com/xuelongqy/flutter_easyrefresh:
  flutter_easyrefresh : ^2.2.1

  image_picker: ^0.8.1
  fluttertoast: ^8.0.7
  #https://pub.dev/packages/sqflite 数据库管理 相当于sqllite
  sqflite: ^2.0.0+3
  cached_network_image: ^3.0.0
  package_info: ^2.0.2
  common_utils: ^2.0.2
  # 扫码 https://github.com/juliuscanute/qr_code_scanner
  qr_code_scanner: 0.5.2
#  qrscan: ^0.3.2
  qr_flutter: ^4.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  json2entity: ^1.0.9
  json_serializable: ^3.5.1
  build_runner: ^1.10.2 #json数据生成实体类
#  json_serializable: ^4.1.3 #json数据生成实体类

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
dependency_overrides:
#  analyzer: ^0.41.1
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
  # assets-generator-begin
  # assets/img/*
    - assets/img/me_item_4.png
    - assets/img/ic_wallet_item_2.png
    - assets/img/ic_score_1.png
    - assets/img/login_phone.png
    - assets/img/ic_down.png
    - assets/img/ic_wallet_item_3.png
    - assets/img/ic_withdraw_address.png
    - assets/img/icon_bank.png
    - assets/img/me_item_5.png
    - assets/img/ic_arrow_right.png
    - assets/img/me_item_7.png
    - assets/img/ic_online.png
    - assets/img/ic_erweima.png
    - assets/img/ic_score_2.png
    - assets/img/ic_wallet_item_1.png
    - assets/img/ic_withdrawal_n.png
    - assets/img/ic_more_item.png
    - assets/img/icon_close.png
    - assets/img/tab_home_n.png
    - assets/img/tab_me_n.png
    - assets/img/me_item_6.png
    - assets/img/icon_display.png
    - assets/img/me_item_2.png
    - assets/img/ic_wallet_item_4.png
    - assets/img/ic_expired.png
    - assets/img/my_wallet_fil.png
    - assets/img/ic_like.png
    - assets/img/ic_eth.png
    - assets/img/me_item_3.png
    - assets/img/home_item_treasure.png
    - assets/img/ic_withdraw_scan.png
    - assets/img/ic_buy_sucess.png
    - assets/img/me_item_1.png
    - assets/img/home_notice.png
    - assets/img/ic_used.png
    - assets/img/tab_quotes_p.png
    - assets/img/home_item_monitoring.png
    - assets/img/icon_hide.png
    - assets/img/edittext_show.png
    - assets/img/ic_image_bg.png
    - assets/img/ic_coupon.png
    - assets/img/my_wallet_nets.png
    - assets/img/ic_light.png
    - assets/img/tab_market_n.png
    - assets/img/icon_wallet.png
    - assets/img/ic_write_more.png
    - assets/img/icon_cny.png
    - assets/img/ic_pay_del.png
    - assets/img/ic_home_get.png
    - assets/img/home_item_3.png
    - assets/img/tab_find_p.png
    - assets/img/ic_add.png
    - assets/img/ic_white_back.png
    - assets/img/title_bar_head.jpg
    - assets/img/ic_address_edit.png
    - assets/img/ic_quote-down.png
    - assets/img/ic_quote_up.png
    - assets/img/ic_unlike.png
    - assets/img/ic_cny_icon.png
    - assets/img/me_item_19.png
    - assets/img/ic_dark_search.png
    - assets/img/home_item_4.png
    - assets/img/home_item_mining.png
    - assets/img/ic_pay_del1.png
    - assets/img/home_item_5.png
    - assets/img/ic_sub.png
    - assets/img/me_item_18.png
    - assets/img/more_item_9.png
    - assets/img/edittext_clear.png
    - assets/img/ic_dot.png
    - assets/img/ic_worring.png
    - assets/img/ic_str.png
    - assets/img/more_item_8.png
    - assets/img/my_wallet_btc.png
    - assets/img/ic_get.png
    - assets/img/ic_add_file.png
    - assets/img/icon_usdt_used.png
    - assets/img/ic_welcome.jpeg
    - assets/img/ic_cny_rechage.png
    - assets/img/me_item_16.png
    - assets/img/tab_market_p.png
    - assets/img/ic_btc.png
    - assets/img/icon_cny_used.png
    - assets/img/ic_big_bg.png
    - assets/img/more_item_13.png
    - assets/img/edittext_hide.png
    - assets/img/more_item_5.png
    - assets/img/ic_dad.png
    - assets/img/login_pwd.png
    - assets/img/tab_find_n.png
    - assets/img/ic_vip.png
    - assets/img/more_item_4.png
    - assets/img/more_item_12.png
    - assets/img/me_item_17.png
    - assets/img/ic_net_address.png
    - assets/img/ic_edit.png
    - assets/img/me_item_15.png
    - assets/img/more_item_10.png
    - assets/img/more_item_6.png
    - assets/img/ic_choose_image.png
    - assets/img/home_monitor.png
    - assets/img/more_item_11.png
    - assets/img/ic_exchange.png
    - assets/img/me_item_14.png
    - assets/img/ic_placeholder.png
    - assets/img/del.png
    - assets/img/me_item_10.png
    - assets/img/ic_envelope.png
    - assets/img/ic_search.png
    - assets/img/ic_arrow.png
    - assets/img/more_item_3.png
    - assets/img/ic_copy.png
    - assets/img/ic_launcher.png
    - assets/img/ic_cny_withdrawal.png
    - assets/img/more_item_2.png
    - assets/img/ic_sold.png
    - assets/img/more_item_14.png
    - assets/img/me_item_11.png
    - assets/img/login_code.png
    - assets/img/ic_def_head.png
    - assets/img/home_item_wallet.png
    - assets/img/me_item_13.png
    - assets/img/ic_play.png
    - assets/img/icon_usdt.png
    - assets/img/ic_launcher_round.png
    - assets/img/more_item_1.png
    - assets/img/home_treasure.png
    - assets/img/me_item_12.png
    - assets/img/ic_up.png
    - assets/img/my_wallet_usdt.png
    - assets/img/ic_add_photo.png
    - assets/img/market_recomed.png
    - assets/img/my_wallet_eth.png
    - assets/img/ic_del.png
    - assets/img/more.png
    - assets/img/ic_fil.png
    - assets/img/tab_home_p.png
    - assets/img/tab_me_p.png
    - assets/img/ic_masonry.png
    - assets/img/icon_alipay.png
    - assets/img/back.png
    - assets/img/my_wallet_eos.png
    - assets/img/me_item_8.png
    - assets/img/tab_quotes_n.png
    - assets/img/ic_bnbb.png
    - assets/img/me_item_9.png
  # assets-generator-end
flutter_intl:
  enabled: true
